repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
      - id: pyright
        args: [--project, pyproject.toml]
        additional_dependencies: ['networkx', 'pyyaml', 'pandas', 'pandas-stubs']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
        files: ^ngraph/schemas/.*\.json$
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: validate-schema
        name: Validate YAML schemas
        entry: make validate
        language: system
        files: ^scenarios/.*\.yaml$
        pass_filenames: false
