site_name: NetGraph
site_url: https://networmix.github.io/NetGraph/
repo_url: https://github.com/networmix/NetGraph
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.copy
markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences  # <-- enables nested fences
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/tutorial.md
  - Examples:
      - Bundled Scenarios: examples/bundled-scenarios.md
      - Basic Example: examples/basic.md
      - Clos Fabric: examples/clos-fabric.md
  - Reference:
      - Design: reference/design.md
      - DSL: reference/dsl.md
      - Workflow: reference/workflow.md
      - CLI: reference/cli.md
      - Schemas: reference/schemas.md
      - API: reference/api.md
      - API Full: reference/api-full.md
plugins:
  - search
strict: true
