name: docs
on:
  push:
    branches: [main]
    paths-ignore: [.github/**, '*.md']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install "mkdocs-material>=9,<10" pdoc
      - run: mkdocs gh-deploy --force --clean
